Added env_variable_setup.rst walkthrough and images
spotipy-dev/spotipy pull request #1056
Opened 2023-12-12 20:01 UTC by moguetn

See changelog for details

2023-12-12 20:02 UTC, moguetn commented
This is my first time contributing - please let me know if I did anything incorrectly!

2024-05-30 19:15 UTC, stephanebruckert approved these changes

2024-05-30 19:22 UTC, stephanebruckert requested changes
This still needs to be linked from index.rst

You can take this repo as an example:
- https://github.com/readthedocs/sphinx_rtd_theme/blob/master/docs/index.rst
- https://sphinx-rtd-theme.readthedocs.io/en/stable/

2025-01-12 16:01 UTC, stephanebruckert commented
Closing as much of this is now part of the doc

2025-01-12 16:01 UTC, closed without merging