update tutorial.md add tips section
spotipy-dev/spotipy pull request #1061
Opened 2023-12-13 04:05 UTC by isaac-tb1010

I would like to share details on how Spotify returns its data and how to access information with Python - a tips section if you will. I added a small tutorial/code block to assist. I would also like to add a walkthrough for the code flow sections since the code isn’t explained.

2024-03-07 18:12 UTC, spire-carlos approved these changes

2024-06-11 08:18 UTC, dieser-niko requested changes
I've added some suggestions that would improve the document a bit.

2024-06-11 08:18 UTC, dieser-niko commented on TUTORIAL.md
> +                                              'ZA'],
Please minimize this.

2024-06-11 08:18 UTC, dieser-niko commented on TUTORIAL.md
> +The data returned is an object of type dictionary. Accessing the data is quite easy and then can be transformed into json and string format. Below is an example of what is returned from querying the
> can be transformed into json and string format.

The wording could be improved. It reads like the user has to transform the json output themselves.

```suggestion
The data returned is an object of type dictionary. Accessing the data is quite easy as the library already parses the JSON response. Below is an example of what is returned from querying the API for a user's top tracks.
```

2024-06-11 08:18 UTC, dieser-niko commented on TUTORIAL.md
> +```
Add language to code block

```suggestion
```python
```

2024-06-11 08:18 UTC, dieser-niko commented on TUTORIAL.md
> +```
```suggestion
```python
```

2024-06-11 08:18 UTC, dieser-niko commented on TUTORIAL.md
> +```
```suggestion
```python
```

2024-07-09 19:19 UTC, stephanebruckert commented
Closing as we already have enough examples in https://github.com/spotipy-dev/spotipy/tree/master/examples

2024-07-09 19:19 UTC, closed without merging