Changed cache_handler.py to utilize Python's Context Management Protocol
spotipy-dev/spotipy pull request #991
Opened 2023-06-12 18:23 UTC by 508chris

I changed two methods within the CacheHandler class, get_cached_token and save_token_to_cache. Instead of opening and closing files manually, I updated these methods to use Python's "with" statement to keep up with good practice in Python programming. 
This will also alleviate any errors that occur before the file is closed which would result in allocated resources. 
Using the with statement, it simplifies the code as well as provides more reliability to the code base. 

I also added an except clause to the get_cached_token method to handle any json decode errors. 

Let me know if you have any questions at all.

2023-06-12 18:35 UTC, 508chris commented
updated change log

2025-01-12 15:30 UTC, stephanebruckert requested changes
Fixed conflicts but something is wrong with the tests

> TypeError: 'Mock' object does not support the context manager protocol

I know this is from a long time ago but any chance you can have another look? Thanks!

2025-01-12 15:30 UTC, stephanebruckert commented on spotipy/cache_handler.py
> +        except IOError as error:
Let's try to also use OSError as it's more general and can catch more issues.

The master branch is currently using OSError https://github.com/spotipy-dev/spotipy/blob/2.25.0/spotipy/cache_handler.py#L84 since https://github.com/spotipy-dev/spotipy/pull/1065

2025-01-12 23:11 UTC, 508chris commented on spotipy/cache_handler.py
> +        except IOError as error:
Hey! I see the issue with the mock object not supporting the context manager. I'll also swap back to OSError. 

Working on the Mock updates now and will test locally. I’ll push the changes once everything is working. 

Thank you!

2025-01-13 19:49 UTC, 508chris commented
Made some updates to the unit tests. The main issue was incorrect handling of the open function, which didn’t support the context manager protocol when mocked. 
I used mock_open with a custom side_effect to properly simulate file handling behavior.

Let me know what you think and/or if there is anything else needed from my end. 
Thank you!

2025-01-14 17:13 UTC, stephanebruckert commented
Thanks for the quick updates! Tests ran but seem to be failing, please can you check again? 🙏 

I've now relaxed the rule that prevented to run the github action workflow for first-time contributors, so if you push, you will be able to see if it passes directly.

2025-01-16 16:20 UTC, 508chris commented
Hi! Sorry about that. Thank you for looking into it. Yes I am checking again and will ensure the tests pass. 
Also thanks for making the making the rule more lenient.

2025-01-18 22:43 UTC, stephanebruckert approved these changes

2025-01-19 00:33 UTC, stephanebruckert commented
Tests still not passing (I modified the workflows again so we can see the results directly, hopeful they always run now).

I also got a version working for the file context manager and mocking, feel free to copy everything from it https://github.com/spotipy-dev/spotipy/compare/master...context-manager-mock

2025-01-19 00:33 UTC, stephanebruckert requested changes
Approved by mistake as checks were green but they didn't include all tests

2025-01-19 01:54 UTC, 508chris commented
Apologies for the confusion — I was pushing and syncing changes to my forked version while testing the workflow, but I haven't finalized all the fixes yet. I’ll review the updates in your version to see how they compare with my current progress.

Thank you for staying on top of this and for the helpful pointers. I’ll finalize my changes by tomorrow or the day after and push everything again for review.

2025-01-19 01:57 UTC, stephanebruckert commented
np, thanks!

2025-01-20 19:07 UTC, 508chris commented
Hey, I am testing out your context-manager-mock branch and getting fails/errors locally. The failures are due to (I believe) hitting spotify api limits. Also seeing failures for SSL errors. Have you experienced anything similar?

2025-01-20 21:34 UTC, 508chris commented
Actually - all tests passed on my fork when I pushed some changes. I believe the tests are failing on the upstream repository side as I do not have access to configure the required secrets for the workflow. Let me know what you think. Thank you!

2025-01-22 23:36 UTC, stephanebruckert approved these changes

2025-01-22 23:36 UTC, merged

2025-01-22 23:39 UTC, stephanebruckert commented
> I believe the tests are failing on the upstream repository side as I do not have access to configure the required secrets for the workflow

That's right! I've merged it and it all passed https://github.com/spotipy-dev/spotipy/actions/runs/12919090082

Awesome stuff thank you for jumping on this again after a year!

2025-01-22 23:47 UTC, 508chris commented
I only added those mocks as I was getting errors on test_add_to_queue tests due to "missing 1 required positional argument: 'mock_post'". Might've been missing something sorry bout that. 


Thank you for looking into this as well as working with me on it. Learned a lot and very appreciative of the opportunity to contribute. 

Thanks again! 
-Chris

2025-01-23 18:06 UTC, dieser-niko commented on spotipy/cache_handler.py
> +                logger.warning("Couldn't read cache at: %s", self.cache_path)
added them back, only two places used %s, so no big deal.